import { Adventurer } from "../adventurer";

export const ADVENTURERS: Adventurer[] = [
  { id: 11, 
    name: 'Nakoa',
    tier: 1,
    tags: ['pc'],
    profession: 'Beggar',
    lineage: 'Human',
    physicalPower: 1,
    physicalAcuity: 1,
    physicalResilience: 1,
    mentalPower: 1,
    mentalAcuity: 1,
    mentalResilience: 1,
    enduranceCurrent: 1,
    enduranceMax: 1,
    deathResistCurrent: 1,
    deathResistMax: 1,
    energyCurrent: 1,
    energyMax: 2,
    focusSlotsCurrent: 1,
    focusSlotsMax: 1,
    movement: 1,
    combatSpeed: 1,
    lethality: 1,
    force: 1,
    resistance: 1,
    defence: 1, 
  },
]